### ISSUE TITLE
Expressions with operations on concretes should be interned simplified

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#236]
We might want to simplify when interning for operations like `add`, `pow2`, etc between two constants, because currently these are done in the `ExprIdx` implementations of `add`, `pow2` helper functions but these aren't enforced to be used everywhere (such as in the old `Subst` code, fixed in #235), leading to non-concrete expressions that are actually fully concrete. Moving this optimization into `intern` itself would simply save some headache on that part, but this might need to be discussed.

**Comment by rachitnigam** [comment]
Yeah, that seems reasonable to me but it's somewhat tricky because the `Component::add` implementation for `Expr` adds things into the store in an unsimplified manner. If we try to change it (#220), the stack overflows because the `ExprIdx` "smart" constructors need to call `Component::add` as the back-off case.

There is a `Simplify` pass that attempts some simplification but that's somewhat different from this issue.

**Comment by UnsignedByte** [comment]
Yes but I was thinking we could just move the "smart"ness of the `ExprIdx` constructors directly into the component add, so infinite recursion should not become an issue.  In fact, recursion should not be a problem at all because all already-interned expressions will be simplified so should need to be no recursive call.

**Comment by rachitnigam** [comment]
Sure! I'm not opposed to the change!
