### ISSUE TITLE
`--show-models` flag leads to unreachable code errors.

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#320]
Example of the error is shown below:

![image](https://github.com/cucapra/filament/assets/34429084/4c8997f4-9c3f-48d6-816a-f93ccff284e5)

(first run with `--show-models`, then without.)

**Comment by rachitnigam** [comment]
This is a cvc5 problem. Can you use —solver z3

**Comment by rachitnigam** [comment]
The problem is that we generate symbols like `|foo.bar|` and in its generated model cvc5 renames them to `foo.bar`. The fix would be to try both `|foo.bar|` and `foo.bar` here: https://github.com/cucapra/filament/blob/main/src/ir_passes/discharge.rs#L216

@UnsignedByte in case you want to take a shot at fixing this.
