### ISSUE TITLE
Multidimensional Bundles

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#351]
As the title says, we should have support for multidimensional bundles. I'm thinking something like this:
```
bundle a[10][20]: for<i, j> ['G, 'G + i + j + 1] 32;
```
where `i` ranges from `0` to `9` and `j` from `0` to `19`.

These can probably be eliminated by the IR if we group everything into one dimension like so:
```
bundle a[10*20]: for <k> ['G, 'G + k/10 + k-((k/10)*10) + 1] 32;
```

**Comment by rachitnigam** [comment]
Yeah, this is a common problem that I've run into as well, for example with the reshape operators. The big question for me is how to represent this in the IR. Do we add these to the IR or do we eliminate them beforehand. If we eliminate them, then we should figure out what `assert` statements we need to add to make the checks succeed (which is another benefit of using multi-dimensional accesses).

**Comment by rachitnigam** [comment]
Let's document some more complex use cases for multi-dimensional bundles from the existing designs.

**Comment by rachitnigam** [comment]
The pipelined FFT:
```
bundle data[(NStages+1) * NPoints * 2]: for<i> ['G+i/(NPoints*2) * L, 'G + i/(NPoints*2) * L + 1] W;
```

To make it more clear what's going on here, we can rewrite using `R = NStages + 1` and `C = NPoints * 2`:
```
bundle data[R * C]: for<i> ['G + i/C * L, ...]
```
We're essentially saying that everything in a particular column has the same latency and going between rows increments the latency by `L`.

Which can be rewritten:
```
bundle data[R][C]: for<i, _> ['G + i*L, 'G + i*L+1]
```
Because we have access to two distinct iterators, we can say that only changing the row changes the latency.

A big win from this is that we get rid of the `/` operator from the liveness of the bundle which is important in making the assertions scale better (as seen in #348).
